In [3]:
import tensorflow as tf

x1_data = [73.,93.,89.,96.,73.]
x2_data = [80., 88., 91., 98., 66.]
x3_data = [75., 93., 90., 100., 70.]

y_data = [152., 185., 180., 196., 142.]

# placeholders for a tensor that will be always fed
x1 = tf.placeholder(tf.float32)
x2 = tf.placeholder(tf.float32)
x3 = tf.placeholder(tf.float32)

Y = tf.placeholder(tf.float32)

w1 = tf.Variable(tf.random_normal([1]), name = 'weight1')
w2 = tf.Variable(tf.random_normal([1]), name = 'weight2')
w3 = tf.Variable(tf.random_normal([1]), name = 'weight3')
b = tf.Variable(tf.random_normal([1]), name = 'bias')

hypothesis = x1*w1 + x2*w2 + x3*w3 + b

# cost/loss function
cost = tf.reduce_mean(tf.square(hypothesis - Y))

# Minimize
# need a very small learning rate for this data set
optimizer = tf.train.GradientDescentOptimizer(learning_rate = 1e-5)
train = optimizer.minimize(cost)

# Launch the graph in a session
sess = tf.Session()

# Initializes global variables in the graph
sess.run(tf.global_variables_initializer())

for step in range(2001):
    cost_val, hy_val, _ = sess.run([cost, hypothesis, train],
                                   feed_dict={x1: x1_data, x2: x2_data, x3: x3_data, Y: y_data})
    if step % 10 == 0:
        print(step, "Cost: ", cost_val, "\nPrediction:\n", hy_val)


0 Cost:  2262.713 
Prediction:
 [102.41045 138.82663 128.66646 141.73618 108.19518]
10 Cost:  20.073572 
Prediction:
 [144.31927 189.1654  178.28305 195.76506 146.58482]
20 Cost:  19.949074 
Prediction:
 [144.46321 189.30597 178.43846 195.93196 146.68591]
30 Cost:  19.845621 
Prediction:
 [144.48076 189.2947  178.44421 195.9359  146.6712 ]
40 Cost:  19.742813 
Prediction:
 [144.49786 189.283   178.44952 195.93935 146.6562 ]
50 Cost:  19.640575 
Prediction:
 [144.51492 189.27136 178.4548  195.94278 146.64124]
60 Cost:  19.5388 
Prediction:
 [144.53195 189.25974 178.46007 195.94621 146.6263 ]
70 Cost:  19.437634 
Prediction:
 [144.54893 189.24815 178.46532 195.94963 146.61142]
80 Cost:  19.336948 
Prediction:
 [144.56586 189.23657 178.47057 195.95303 146.59656]
90 Cost:  19.23689 
Prediction:
 [144.58273 189.22504 178.47577 195.95642 146.58176]
100 Cost:  19.137272 
Prediction:
 [144.59958 189.21353 178.48097 195.9598  146.56697]
110 Cost:  19.038265 
Prediction:
 [144.61638 189.20207 17

1000 Cost:  12.059823 
Prediction:
 [145.94414 188.29529 178.89738 196.22652 145.39111]
1010 Cost:  11.998907 
Prediction:
 [145.95732 188.28627 178.90147 196.2291  145.37961]
1020 Cost:  11.938353 
Prediction:
 [145.97046 188.27728 178.90555 196.23166 145.36813]
1030 Cost:  11.878084 
Prediction:
 [145.9836  188.26834 178.90962 196.23424 145.3567 ]
1040 Cost:  11.818172 
Prediction:
 [145.99669 188.25941 178.91368 196.23679 145.34532]
1050 Cost:  11.758532 
Prediction:
 [146.00975 188.2505  178.91776 196.23935 145.33395]
1060 Cost:  11.699214 
Prediction:
 [146.02278 188.24162 178.9218  196.2419  145.32262]
1070 Cost:  11.640261 
Prediction:
 [146.03575 188.23276 178.9258  196.24442 145.3113 ]
1080 Cost:  11.5816145 
Prediction:
 [146.04869 188.2239  178.92981 196.24695 145.30002]
1090 Cost:  11.523298 
Prediction:
 [146.06158 188.21509 178.9338  196.24945 145.28876]
1100 Cost:  11.465245 
Prediction:
 [146.07448 188.2063  178.93779 196.25197 145.27754]
1110 Cost:  11.40754 
Predictio

1960 Cost:  7.482486 
Prediction:
 [147.0626  187.53218 179.24472 196.44174 144.42014]
1970 Cost:  7.4461565 
Prediction:
 [147.07283 187.52522 179.2479  196.44368 144.41133]
1980 Cost:  7.410032 
Prediction:
 [147.083   187.51826 179.25104 196.44557 144.40251]
1990 Cost:  7.374138 
Prediction:
 [147.09314 187.51135 179.25421 196.44751 144.39375]
2000 Cost:  7.338353 
Prediction:
 [147.10329 187.50444 179.25737 196.44942 144.38501]


In [4]:
# matrix를 이용하여 구현하기
import tensorflow as tf

# 위 예제와 달리 간단해짐
x_data = [[73., 80., 75.],
          [93., 88., 93.],
          [89., 91., 90.],
          [96., 98., 100.],
          [73., 66., 70.]]
y_data = [[152.],
          [185.],
          [180.],
          [196.],
          [142.]]

# placeholders for a tensor that will be always fed.
# shape 주의 -> none(instance의 개수가 정해져 있지 않다 n개)
X = tf.placeholder(tf.float32, shape=[None, 3])
Y = tf.placeholder(tf.float32, shape=[None, 1])

W = tf.Variable(tf.random_normal([3, 1]), name='weight')
b = tf.Variable(tf.random_normal([1]), name='bias')

# Hypothesis
# matmul : 행렬
hypothesis = tf.matmul(X, W) + b

# Simplified cost/loss function
cost = tf.reduce_mean(tf.square(hypothesis - Y))

# Minimize
optimizer = tf.train.GradientDescentOptimizer(learning_rate=1e-5)
train = optimizer.minimize(cost)

# Launch the graph in a session.
sess = tf.Session()

# Initializes global variables in the graph.
sess.run(tf.global_variables_initializer())

for step in range(2001):
    cost_val, hy_val, _ = sess.run(
        [cost, hypothesis, train], feed_dict={X: x_data, Y: y_data})
    if step % 10 == 0:
        print(step, "Cost: ", cost_val, "\nPrediction:\n", hy_val)

0 Cost:  29712.8 
Prediction:
 [[-3.266284  ]
 [ 2.098281  ]
 [-0.88226783]
 [-1.8484391 ]
 [ 3.64919   ]]
10 Cost:  2.2915013 
Prediction:
 [[149.2186 ]
 [185.36389]
 [179.69759]
 [194.79797]
 [143.43268]]
20 Cost:  2.009705 
Prediction:
 [[149.68517]
 [185.91484]
 [180.24556]
 [195.39417]
 [143.85089]]
30 Cost:  1.9999764 
Prediction:
 [[149.69176]
 [185.91298]
 [180.2488 ]
 [195.3972 ]
 [143.84746]]
40 Cost:  1.9903091 
Prediction:
 [[149.69693]
 [185.90942]
 [180.25038]
 [195.3984 ]
 [143.84276]]
50 Cost:  1.9806988 
Prediction:
 [[149.70207]
 [185.90588]
 [180.25194]
 [195.39961]
 [143.83806]]
60 Cost:  1.9711239 
Prediction:
 [[149.70721]
 [185.90236]
 [180.2535 ]
 [195.4008 ]
 [143.83336]]
70 Cost:  1.9615977 
Prediction:
 [[149.71234]
 [185.89883]
 [180.25507]
 [195.40201]
 [143.82867]]
80 Cost:  1.9521425 
Prediction:
 [[149.71745]
 [185.89532]
 [180.25664]
 [195.4032 ]
 [143.82402]]
90 Cost:  1.9427239 
Prediction:
 [[149.72255]
 [185.89182]
 [180.25818]
 [195.40439]
 [143.81

900 Cost:  1.3270239 
Prediction:
 [[150.09267]
 [185.63754]
 [180.37088]
 [195.49117]
 [143.48131]]
910 Cost:  1.3209848 
Prediction:
 [[150.09676]
 [185.63475]
 [180.37212]
 [195.49211]
 [143.47758]]
920 Cost:  1.3149667 
Prediction:
 [[150.10083]
 [185.63196]
 [180.37337]
 [195.4931 ]
 [143.47386]]
930 Cost:  1.3089926 
Prediction:
 [[150.10487]
 [185.62917]
 [180.37459]
 [195.49405]
 [143.47014]]
940 Cost:  1.3030585 
Prediction:
 [[150.10893]
 [185.62639]
 [180.37584]
 [195.495  ]
 [143.46646]]
950 Cost:  1.2971506 
Prediction:
 [[150.11296]
 [185.62363]
 [180.37706]
 [195.49596]
 [143.46277]]
960 Cost:  1.2912661 
Prediction:
 [[150.11699]
 [185.62085]
 [180.3783 ]
 [195.49692]
 [143.45909]]
970 Cost:  1.2854145 
Prediction:
 [[150.121  ]
 [185.61809]
 [180.3795 ]
 [195.49785]
 [143.45541]]
980 Cost:  1.2796074 
Prediction:
 [[150.12498]
 [185.61534]
 [180.38072]
 [195.49878]
 [143.45174]]
990 Cost:  1.2738208 
Prediction:
 [[150.12898]
 [185.61261]
 [180.38193]
 [195.49973]
 [14

1730 Cost:  0.92209136 
Prediction:
 [[150.39598]
 [185.42911]
 [180.46312]
 [195.56316]
 [143.20338]]
1740 Cost:  0.9182369 
Prediction:
 [[150.39923]
 [185.42688]
 [180.4641 ]
 [195.56392]
 [143.2004 ]]
1750 Cost:  0.9144171 
Prediction:
 [[150.40245]
 [185.42464]
 [180.46507]
 [195.56468]
 [143.19742]]
1760 Cost:  0.91061056 
Prediction:
 [[150.40569]
 [185.42242]
 [180.46608]
 [195.56548]
 [143.19446]]
1770 Cost:  0.90679914 
Prediction:
 [[150.40894]
 [185.42021]
 [180.46706]
 [195.56627]
 [143.1915 ]]
1780 Cost:  0.903025 
Prediction:
 [[150.41214]
 [185.418  ]
 [180.46803]
 [195.56703]
 [143.18852]]
1790 Cost:  0.8992799 
Prediction:
 [[150.41534]
 [185.41579]
 [180.469  ]
 [195.5678 ]
 [143.1856 ]]
1800 Cost:  0.89555246 
Prediction:
 [[150.41853]
 [185.41359]
 [180.46996]
 [195.56854]
 [143.18265]]
1810 Cost:  0.89184266 
Prediction:
 [[150.42172]
 [185.41139]
 [180.47093]
 [195.5693 ]
 [143.17972]]
1820 Cost:  0.8881496 
Prediction:
 [[150.42491]
 [185.4092 ]
 [180.4719 ]
 [1

# loading data from file
numpy의 loadtext를 이용

In [11]:
import tensorflow as tf
import numpy as np

# delimiter : 구분자
# 2차원 array로 데이터를 가져 온다
xy = np.loadtxt('C:\python\data-01-test-score.csv', delimiter=',', dtype=np.float32)
type(xy)
x_data = xy[:, 0:-1]
y_data = xy[:, [-1]]

# Make sure the shape and data are OK
print(x_data, "\nx_data shape:", x_data.shape)
print(y_data, "\ny_data shape:", y_data.shape)

# Hypothesis
hypothesis = tf.matmul(X, W) + b

# Simplified cost/loss function
cost = tf.reduce_mean(tf.square(hypothesis - Y))

# Minimize
optimizer = tf.train.GradientDescentOptimizer(learning_rate=1e-5)
train = optimizer.minimize(cost)

# Launch the graph in a session.
sess = tf.Session()
# Initializes global variables in the graph.
sess.run(tf.global_variables_initializer())

for step in range(2001):
    cost_val, hy_val, _ = sess.run([cost, hypothesis, train], 
                                   feed_dict={X: x_data, Y: y_data})
    if step % 10 == 0:
        print(step, "Cost:", cost_val, "\nPrediction:\n", hy_val)

        
# Ask my score
print("Your score will be ", sess.run(hypothesis, 
                                      feed_dict={X: [[100, 70, 101]]}))

print("Other scores will be ", sess.run(hypothesis,
                                        feed_dict={X: [[60, 70, 110], [90, 100, 80]]}))


[[73. 80. 75.]
 [93. 88. 93.]
 [89. 91. 90.]
 [73. 66. 70.]] 
x_data shape: (4, 3)
[[152.]
 [185.]
 [180.]
 [142.]] 
y_data shape: (4, 1)
0 Cost: 75705.88 
Prediction:
 [[-100.63048 ]
 [-121.765564]
 [-119.445114]
 [ -93.00827 ]]
10 Cost: 4.786673 
Prediction:
 [[152.11513]
 [182.0635 ]
 [179.89929]
 [138.75958]]
20 Cost: 2.5153356 
Prediction:
 [[153.48822]
 [183.72626]
 [181.53119]
 [140.03033]]
30 Cost: 2.5005238 
Prediction:
 [[153.48892]
 [183.73927]
 [181.53769]
 [140.04263]]
40 Cost: 2.485841 
Prediction:
 [[153.48215]
 [183.74327]
 [181.5353 ]
 [140.04805]]
50 Cost: 2.4712763 
Prediction:
 [[153.47539]
 [183.74722]
 [181.5329 ]
 [140.05344]]
60 Cost: 2.4567885 
Prediction:
 [[153.46861]
 [183.75114]
 [181.53047]
 [140.05878]]
70 Cost: 2.4424167 
Prediction:
 [[153.46187]
 [183.75504]
 [181.52806]
 [140.0641 ]]
80 Cost: 2.428141 
Prediction:
 [[153.45517]
 [183.75896]
 [181.5257 ]
 [140.06943]]
90 Cost: 2.4139714 
Prediction:
 [[153.44847]
 [183.76282]
 [181.5233 ]
 [140.0747 ]]

1100 Cost: 1.3715922 
Prediction:
 [[152.87453]
 [184.0954 ]
 [181.31871]
 [140.52885]]
1110 Cost: 1.3643312 
Prediction:
 [[152.86975]
 [184.09819]
 [181.317  ]
 [140.53265]]
1120 Cost: 1.3571472 
Prediction:
 [[152.86497]
 [184.10094]
 [181.3153 ]
 [140.53642]]
1130 Cost: 1.3500079 
Prediction:
 [[152.86023]
 [184.10367]
 [181.3136 ]
 [140.54018]]
1140 Cost: 1.342912 
Prediction:
 [[152.8555 ]
 [184.10641]
 [181.31192]
 [140.54393]]
1150 Cost: 1.3358569 
Prediction:
 [[152.85078]
 [184.10916]
 [181.31024]
 [140.54767]]
1160 Cost: 1.3288648 
Prediction:
 [[152.8461]
 [184.1119]
 [181.3086]
 [140.5514]]
1170 Cost: 1.3219061 
Prediction:
 [[152.8414]
 [184.1146]
 [181.3069]
 [140.5551]]
1180 Cost: 1.3149883 
Prediction:
 [[152.83675]
 [184.1173 ]
 [181.30522]
 [140.5588 ]]
1190 Cost: 1.3081287 
Prediction:
 [[152.83208]
 [184.12   ]
 [181.30357]
 [140.56248]]
1200 Cost: 1.301308 
Prediction:
 [[152.82744]
 [184.12267]
 [181.30191]
 [140.56616]]
1210 Cost: 1.2945335 
Prediction:
 [[152.8

# Queue Runner

In [13]:
import tensorflow as tf
# file_queue 만들기
filename_queue = tf.train.string_input_producer(['C:\python\data-01-test-score.csv'],shuffle = False, name = 'filename_queue')

# reader 정의
reader = tf.TextLineReader()
key, value = reader.read(filename_queue)

# csv로 decorder
# 이때 각각의 데이터 타입 정의
record_defaults = [[0.], [0.], [0.], [0.]] # float 타입으로 정의
xy = tf.decode_csv(value, record_defaults = record_defaults)

# collect batches of csv
# w,y 데이터 각각 정의해주고 한번 가져 올 때 몇개의 데이터를 가져 로지 정의해줌
train_x_batch, train_y_batch = \
    tf.train.batch([xy[0:-1], xy[-1:]], batch_size=10)

# placeholders for a tensor that will be always fed.
X = tf.placeholder(tf.float32, shape=[None, 3])
Y = tf.placeholder(tf.float32, shape=[None, 1])

W = tf.Variable(tf.random_normal([3, 1]), name='weight')
b = tf.Variable(tf.random_normal([1]), name='bias')

# Hypothesis
hypothesis = tf.matmul(X, W) + b

# Simplified cost/loss function
cost = tf.reduce_mean(tf.square(hypothesis - Y))

# Minimize
optimizer = tf.train.GradientDescentOptimizer(learning_rate=1e-5)
train = optimizer.minimize(cost)

# Launch the graph in a session.
sess = tf.Session()
# Initializes global variables in the graph.
sess.run(tf.global_variables_initializer())

# Start populating the filename queue.
# 그냥 일반적으로 작성하는 부분
coord = tf.train.Coordinator()
threads = tf.train.start_queue_runners(sess=sess, coord=coord)

for step in range(2001):
    x_batch, y_batch = sess.run([train_x_batch, train_y_batch])
    cost_val, hy_val, _ = sess.run(
        [cost, hypothesis, train], feed_dict={X: x_batch, Y: y_batch})
    if step % 10 == 0:
        print(step, "Cost: ", cost_val, "\nPrediction:\n", hy_val)

# 그냥 일반적으로 작성하는 부분
coord.request_stop()
coord.join(threads)

# Ask my score
print("Your score will be ",
      sess.run(hypothesis, feed_dict={X: [[100, 70, 101]]}))

print("Other scores will be ",
      sess.run(hypothesis, feed_dict={X: [[60, 70, 110], [90, 100, 80]]}))

Instructions for updating:
Queue-based input pipelines have been replaced by `tf.data`. Use `tf.data.Dataset.batch(batch_size)` (or `padded_batch(...)` if `dynamic_pad=True`).
Instructions for updating:
To construct input pipelines, use the `tf.data` module.
0 Cost:  16.61801 
Prediction:
 [[149.66858]
 [190.59396]
 [182.18573]
 [146.81879]
 [149.66858]
 [190.59396]
 [182.18573]
 [146.81879]
 [149.66858]
 [190.59396]]
10 Cost:  10.326059 
Prediction:
 [[147.23073]
 [187.6392 ]
 [179.28719]
 [144.5603 ]
 [147.23073]
 [187.6392 ]
 [179.28719]
 [144.5603 ]
 [147.23073]
 [187.6392 ]]
20 Cost:  10.267396 
Prediction:
 [[147.231  ]
 [187.61525]
 [179.27625]
 [144.53749]
 [147.231  ]
 [187.61525]
 [179.27625]
 [144.53749]
 [147.231  ]
 [187.61525]]
30 Cost:  10.204248 
Prediction:
 [[147.24455]
 [187.60736]
 [179.28107]
 [144.52695]
 [147.24455]
 [187.60736]
 [179.28107]
 [144.52695]
 [147.24455]
 [187.60736]]
40 Cost:  10.1414385 
Prediction:
 [[147.25812]
 [187.59955]
 [179.28595]
 [144.516

460 Cost:  7.8400345 
Prediction:
 [[147.78958]
 [187.29425]
 [179.47736]
 [144.10718]
 [147.78958]
 [187.29425]
 [179.47736]
 [144.10718]
 [147.78958]
 [187.29425]]
470 Cost:  7.792451 
Prediction:
 [[147.80138]
 [187.28748]
 [179.48158]
 [144.0981 ]
 [147.80138]
 [187.28748]
 [179.48158]
 [144.0981 ]
 [147.80138]
 [187.28748]]
480 Cost:  7.7452307 
Prediction:
 [[147.81313]
 [187.28075]
 [179.48582]
 [144.08907]
 [147.81313]
 [187.28075]
 [179.48582]
 [144.08907]
 [147.81313]
 [187.28075]]
490 Cost:  7.6983733 
Prediction:
 [[147.8248 ]
 [187.27402]
 [179.49002]
 [144.08005]
 [147.8248 ]
 [187.27402]
 [179.49002]
 [144.08005]
 [147.8248 ]
 [187.27402]]
500 Cost:  7.6517243 
Prediction:
 [[147.83647]
 [187.2673 ]
 [179.49422]
 [144.07108]
 [147.83647]
 [187.2673 ]
 [179.49422]
 [144.07108]
 [147.83647]
 [187.2673 ]]
510 Cost:  7.6054106 
Prediction:
 [[147.8481 ]
 [187.26064]
 [179.49841]
 [144.06212]
 [147.8481 ]
 [187.26064]
 [179.49841]
 [144.06212]
 [147.8481 ]
 [187.26064]]
520 C

980 Cost:  5.73424 
Prediction:
 [[148.35336]
 [186.97006]
 [179.68028]
 [143.67342]
 [148.35336]
 [186.97006]
 [179.68028]
 [143.67342]
 [148.35336]
 [186.97006]]
990 Cost:  5.7002816 
Prediction:
 [[148.36328]
 [186.96436]
 [179.68387]
 [143.66579]
 [148.36328]
 [186.96436]
 [179.68387]
 [143.66579]
 [148.36328]
 [186.96436]]
1000 Cost:  5.6665387 
Prediction:
 [[148.37317]
 [186.95866]
 [179.68742]
 [143.65819]
 [148.37317]
 [186.95866]
 [179.68742]
 [143.65819]
 [148.37317]
 [186.95866]]
1010 Cost:  5.632988 
Prediction:
 [[148.38303]
 [186.95299]
 [179.69096]
 [143.65059]
 [148.38303]
 [186.95299]
 [179.69096]
 [143.65059]
 [148.38303]
 [186.95299]]
1020 Cost:  5.599656 
Prediction:
 [[148.39285]
 [186.94733]
 [179.6945 ]
 [143.64304]
 [148.39285]
 [186.94733]
 [179.6945 ]
 [143.64304]
 [148.39285]
 [186.94733]]
1030 Cost:  5.566556 
Prediction:
 [[148.40265]
 [186.9417 ]
 [179.69801]
 [143.63551]
 [148.40265]
 [186.9417 ]
 [179.69801]
 [143.63551]
 [148.40265]
 [186.9417 ]]
1040 

1480 Cost:  4.277433 
Prediction:
 [[148.8115 ]
 [186.7063 ]
 [179.84512]
 [143.32141]
 [148.8115 ]
 [186.7063 ]
 [179.84512]
 [143.32141]
 [148.8115 ]
 [186.7063 ]]
1490 Cost:  4.25279 
Prediction:
 [[148.81992]
 [186.70145]
 [179.84816]
 [143.31496]
 [148.81992]
 [186.70145]
 [179.84816]
 [143.31496]
 [148.81992]
 [186.70145]]
1500 Cost:  4.228329 
Prediction:
 [[148.8283 ]
 [186.69661]
 [179.85117]
 [143.3085 ]
 [148.8283 ]
 [186.69661]
 [179.85117]
 [143.3085 ]
 [148.8283 ]
 [186.69661]]
1510 Cost:  4.203998 
Prediction:
 [[148.83667]
 [186.6918 ]
 [179.85419]
 [143.3021 ]
 [148.83667]
 [186.6918 ]
 [179.85419]
 [143.3021 ]
 [148.83667]
 [186.6918 ]]
1520 Cost:  4.1798606 
Prediction:
 [[148.84499]
 [186.687  ]
 [179.85718]
 [143.29568]
 [148.84499]
 [186.687  ]
 [179.85718]
 [143.29568]
 [148.84499]
 [186.687  ]]
1530 Cost:  4.1558533 
Prediction:
 [[148.8533 ]
 [186.68222]
 [179.86017]
 [143.28932]
 [148.8533 ]
 [186.68222]
 [179.86017]
 [143.28932]
 [148.8533 ]
 [186.68222]]
154

1990 Cost:  3.2027004 
Prediction:
 [[149.20718]
 [186.47818]
 [179.98741]
 [143.01788]
 [149.20718]
 [186.47818]
 [179.98741]
 [143.01788]
 [149.20718]
 [186.47818]]
2000 Cost:  3.184967 
Prediction:
 [[149.21428]
 [186.47408]
 [179.98997]
 [143.01244]
 [149.21428]
 [186.47408]
 [179.98997]
 [143.01244]
 [149.21428]
 [186.47408]]
Your score will be  [[199.71255]]
Other scores will be  [[172.58235]
 [171.38008]]
