# Evaluation and Learning rate
모델을 평가할 때는 한번도 학습하지 않은 test dataset으로 해야 한다

In [6]:
import tensorflow as tf
# dataset을 training dataset과 test dataset으로 나눈다
x_data = [[1, 2, 1],
          [1, 3, 2],
          [1, 3, 4],
          [1, 5, 5],
          [1, 7, 5],
          [1, 2, 5],
          [1, 6, 6],
          [1, 7, 7]]
y_data = [[0, 0, 1],
          [0, 0, 1],
          [0, 0, 1],
          [0, 1, 0],
          [0, 1, 0],
          [0, 1, 0],
          [1, 0, 0],
          [1, 0, 0]]

# Evaluation our model using test dataset
x_test = [[2, 1, 1],
          [3, 1, 2],
          [3, 3, 4]]
y_test = [[0, 0, 1],
          [0, 0, 1],
          [0, 0, 1]]

X = tf.placeholder("float", [None, 3])
Y = tf.placeholder("float", [None, 3])

W = tf.Variable(tf.random_normal([3,3]))
b = tf.Variable(tf.random_normal([3]))

# tf.nn.softmax computes softmax activations
hypothesis = tf.nn.softmax(tf.matmul(X, W) + b)

# cross entropy cost/loss
cost = tf.reduce_mean(-tf.reduce_sum(Y * tf.log(hypothesis), axis=1))

# Try to change learning_rate
# learningRate가 너무 크면 cost가 숫자가 아닌 값이 나오고
# learningRate가 너무 작으면 학습이 제대로 이뤄지지 않아 많은 시도에도 같은 cost값이 나온다
optimizer = tf.train.GradientDescentOptimizer(learning_rate=0.001).minimize(cost)

# Correct prediction Test model
prediction = tf.argmax(hypothesis, 1)
is_correct = tf.equal(prediction, tf.argmax(Y, 1))
accurancy = tf.reduce_mean(tf.cast(is_correct, tf.float32))

# Launch graph
with tf.Session() as sess:
    # Initialize TensorFlow variables
    sess.run(tf.global_variables_initializer())

    for step in range(201):
        cost_val, W_val, _ = sess.run([cost, W, optimizer], feed_dict={X: x_data, Y: y_data})
        print(step, cost_val, W_val)
        
        # predict
        print("Prediction : ", sess.run(prediction, feed_dict = {X:x_test}))
        # calculate the accurancy
        print('Accurency : ', sess.run(accurancy, feed_dict = {X:x_test, Y:y_test}))


0 3.7079291 [[ 1.4048469  -0.35622627 -0.4307459 ]
 [-0.912007    2.2800484  -1.0890896 ]
 [ 0.30887723 -1.3836564   0.8513939 ]]
Prediction :  [0 0 0]
Accurency :  0.0
1 3.6961598 [[ 1.4050475  -0.35662547 -0.43054727]
 [-0.9105058   2.2779706  -1.088513  ]
 [ 0.31031337 -1.3851715   0.8514729 ]]
Prediction :  [0 0 0]
Accurency :  0.0
2 3.684422 [[ 1.4052476  -0.3570239  -0.4303489 ]
 [-0.909006    2.275895   -1.0879374 ]
 [ 0.31174752 -1.386684    0.8515512 ]]
Prediction :  [0 0 0]
Accurency :  0.0
3 3.6727147 [[ 1.4054471  -0.35742155 -0.43015075]
 [-0.90750766  2.273822   -1.0873626 ]
 [ 0.31317967 -1.3881936   0.8516287 ]]
Prediction :  [0 0 0]
Accurency :  0.0
4 3.6610389 [[ 1.4056461  -0.35781842 -0.42995283]
 [-0.9060108   2.2717514  -1.0867889 ]
 [ 0.31460983 -1.3897005   0.85170555]]
Prediction :  [0 0 0]
Accurency :  0.0
5 3.649395 [[ 1.4058446  -0.35821453 -0.42975515]
 [-0.9045154   2.2696831  -1.0862161 ]
 [ 0.31603795 -1.3912047   0.8517816 ]]
Prediction :  [0 0 0]
Accur

Accurency :  0.0
83 2.8487258 [[ 1.4192859  -0.3865632  -0.41484776]
 [-0.79376113  2.117091   -1.044378  ]
 [ 0.41975865 -1.4992545   0.8561104 ]]
Prediction :  [0 0 0]
Accurency :  0.0
84 2.8400826 [[ 1.4194266  -0.38688958 -0.41466206]
 [-0.7924409   2.115276   -1.0438834 ]
 [ 0.42096576 -1.5004971   0.8561459 ]]
Prediction :  [0 0 0]
Accurency :  0.0
85 2.83149 [[ 1.4195663  -0.3872148  -0.4144765 ]
 [-0.79112405  2.113466   -1.0433903 ]
 [ 0.42216894 -1.5017351   0.8561807 ]]
Prediction :  [0 0 0]
Accurency :  0.0
86 2.8229485 [[ 1.419705   -0.3875389  -0.41429114]
 [-0.78981066  2.1116607  -1.0428984 ]
 [ 0.42336813 -1.5029684   0.8562148 ]]
Prediction :  [0 0 0]
Accurency :  0.0
87 2.814458 [[ 1.4198427  -0.38786185 -0.41410592]
 [-0.7885007   2.1098604  -1.042408  ]
 [ 0.4245633  -1.504197    0.8562482 ]]
Prediction :  [0 0 0]
Accurency :  0.0
88 2.8060195 [[ 1.4199795  -0.38818362 -0.41392085]
 [-0.7871944   2.1080651  -1.041919  ]
 [ 0.42575437 -1.5054207   0.85628086]]
Predi

Prediction :  [0 0 0]
Accurency :  0.0
132 2.49294 [[ 1.4248638  -0.4010277  -0.40596095]
 [-0.73400563  2.0350254  -1.0220684 ]
 [ 0.47336254 -1.5534955   0.8567476 ]]
Prediction :  [0 0 0]
Accurency :  0.0
133 2.4872785 [[ 1.424946   -0.40128598 -0.40578482]
 [-0.7329138   2.033525   -1.02166   ]
 [ 0.47431698 -1.5544338   0.8567315 ]]
Prediction :  [0 0 0]
Accurency :  0.0
134 2.4816852 [[ 1.4250267  -0.4015426  -0.40560892]
 [-0.73182803  2.0320327  -1.0212536 ]
 [ 0.47526497 -1.5553643   0.85671395]]
Prediction :  [0 0 0]
Accurency :  0.0
135 2.47616 [[ 1.4251059  -0.40179756 -0.40543324]
 [-0.73074836  2.0305488  -1.0208492 ]
 [ 0.4762064  -1.5562868   0.85669506]]
Prediction :  [0 0 0]
Accurency :  0.0
136 2.4707038 [[ 1.4251838  -0.40205085 -0.4052578 ]
 [-0.7296749   2.029073   -1.0204469 ]
 [ 0.47714126 -1.5572014   0.85667485]]
Prediction :  [0 0 0]
Accurency :  0.0
137 2.465316 [[ 1.4252602  -0.40230247 -0.40508258]
 [-0.7286076   2.0276055  -1.0200466 ]
 [ 0.47806948 -1.55

Accurency :  0.0
182 2.2897246 [[ 1.4271547  -0.41185707 -0.39742246]
 [-0.68757296  1.9705793  -1.0040544 ]
 [ 0.51248395 -1.5901934   0.85432416]]
Prediction :  [0 0 0]
Accurency :  0.0
183 2.2871432 [[ 1.4271624  -0.41203067 -0.39725664]
 [-0.6868221   1.9695135  -1.0037396 ]
 [ 0.513081   -1.5907115   0.8542452 ]]
Prediction :  [0 0 0]
Accurency :  0.0
184 2.28461 [[ 1.4271687 -0.4122027 -0.397091 ]
 [-0.6860782  1.9684563 -1.0034262]
 [ 0.5136709 -1.5912213  0.8541652]]
Prediction :  [0 0 0]
Accurency :  0.0
185 2.2821236 [[ 1.4271736 -0.4123731 -0.3969255]
 [-0.6853412  1.9674073 -1.0031143]
 [ 0.5142537 -1.5917231  0.8540842]]
Prediction :  [0 0 0]
Accurency :  0.0
186 2.2796836 [[ 1.4271771  -0.41254196 -0.39676017]
 [-0.684611    1.9663668  -1.0028039 ]
 [ 0.51482934 -1.5922167   0.85400224]]
Prediction :  [0 0 0]
Accurency :  0.0
187 2.2772894 [[ 1.4271792  -0.41270924 -0.39659497]
 [-0.6838877   1.9653345  -1.0024949 ]
 [ 0.5153979  -1.5927024   0.8539193 ]]
Prediction :  [0

# data preprocessing
데이터가 너무 크거나 데이터가 너무 들쑥날쑥할 때 data normalize

In [9]:
import tensorflow as tf
import numpy as np

def min_max_scaler(data):
    numerator = data - np.min(data,0)
    denominator = np.max(data,0) - np.min(data,0)
     # noise term prevents the zero division
    return numerator / (denominator + 1e-7)

# 데이터간의 차이가 너무 크다 => non normalized data
xy = np.array([[828.659973, 833.450012, 908100, 828.349976, 831.659973],
               [823.02002, 828.070007, 1828100, 821.655029, 828.070007],
               [819.929993, 824.400024, 1438100, 818.97998, 824.159973],
               [816, 820.958984, 1008100, 815.48999, 819.23999],
               [819.359985, 823, 1188100, 818.469971, 818.97998],
               [819, 823, 1198100, 816, 820.450012],
               [811.700012, 815.25, 1098100, 809.780029, 813.669983],
               [809.51001, 816.659973, 1398100, 804.539978, 809.559998]])
# normalized data
xy = min_max_scaler(xy)

x_data = xy[:, 0:-1]
y_data = xy[:, [-1]]

# placeholders for a tensor that will be always fed.
X = tf.placeholder(tf.float32, shape=[None, 4])
Y = tf.placeholder(tf.float32, shape=[None, 1])

W = tf.Variable(tf.random_normal([4, 1]), name='weight')
b = tf.Variable(tf.random_normal([1]), name='bias')

# Hypothesis
hypothesis = tf.matmul(X, W) + b

# Simplified cost/loss function
cost = tf.reduce_mean(tf.square(hypothesis - Y))

# Minimize
optimizer = tf.train.GradientDescentOptimizer(learning_rate=1e-5)
train = optimizer.minimize(cost)

# Launch the graph in a session.
sess = tf.Session()

# Initializes global variables in the graph.
sess.run(tf.global_variables_initializer())

for step in range(101):
    cost_val, hy_val, _ = sess.run(
        [cost, hypothesis, train], feed_dict={X: x_data, Y: y_data})
    print(step, "Cost: ", cost_val, "\nPrediction:\n", hy_val)




0 Cost:  3.4692025 
Prediction:
 [[-2.4940796 ]
 [-0.4332611 ]
 [-0.94140625]
 [-1.5147734 ]
 [-1.3305318 ]
 [-1.2378112 ]
 [-0.97671545]
 [-0.34230274]]
1 Cost:  3.4689667 
Prediction:
 [[-2.4939876 ]
 [-0.4331764 ]
 [-0.9413347 ]
 [-1.5147171 ]
 [-1.3304656 ]
 [-1.2377473 ]
 [-0.9766733 ]
 [-0.34226286]]
2 Cost:  3.4687304 
Prediction:
 [[-2.4938955 ]
 [-0.43309158]
 [-0.9412633 ]
 [-1.5146607 ]
 [-1.3303992 ]
 [-1.2376833 ]
 [-0.97663116]
 [-0.342223  ]]
3 Cost:  3.4684944 
Prediction:
 [[-2.4938033 ]
 [-0.43300676]
 [-0.9411918 ]
 [-1.5146043 ]
 [-1.3303328 ]
 [-1.2376194 ]
 [-0.976589  ]
 [-0.34218305]]
4 Cost:  3.4682589 
Prediction:
 [[-2.4937112 ]
 [-0.43292195]
 [-0.94112045]
 [-1.5145481 ]
 [-1.3302665 ]
 [-1.2375556 ]
 [-0.97654694]
 [-0.34214324]]
5 Cost:  3.4680228 
Prediction:
 [[-2.4936192 ]
 [-0.43283725]
 [-0.941049  ]
 [-1.5144918 ]
 [-1.3302001 ]
 [-1.2374916 ]
 [-0.9765048 ]
 [-0.34210336]]
6 Cost:  3.4677868 
Prediction:
 [[-2.493527  ]
 [-0.43275243]
 [-0.9409775 

95 Cost:  3.446858 
Prediction:
 [[-2.4853446 ]
 [-0.42521596]
 [-0.9346273 ]
 [-1.5094287 ]
 [-1.3242366 ]
 [-1.2317472 ]
 [-0.9727178 ]
 [-0.33851784]]
96 Cost:  3.446624 
Prediction:
 [[-2.4852529 ]
 [-0.4251315 ]
 [-0.9345562 ]
 [-1.5093727 ]
 [-1.3241705 ]
 [-1.2316835 ]
 [-0.97267586]
 [-0.33847815]]
97 Cost:  3.4463892 
Prediction:
 [[-2.485161  ]
 [-0.42504686]
 [-0.93448484]
 [-1.5093164 ]
 [-1.3241043 ]
 [-1.2316198 ]
 [-0.97263384]
 [-0.3384384 ]]
98 Cost:  3.4461553 
Prediction:
 [[-2.4850693 ]
 [-0.42496246]
 [-0.9344137 ]
 [-1.5092604 ]
 [-1.3240383 ]
 [-1.231556  ]
 [-0.9725919 ]
 [-0.33839858]]
99 Cost:  3.4459207 
Prediction:
 [[-2.4849775 ]
 [-0.42487782]
 [-0.9343424 ]
 [-1.5092041 ]
 [-1.3239721 ]
 [-1.2314924 ]
 [-0.97254986]
 [-0.33835888]]
100 Cost:  3.4456863 
Prediction:
 [[-2.4848857 ]
 [-0.42479336]
 [-0.9342712 ]
 [-1.5091481 ]
 [-1.323906  ]
 [-1.2314286 ]
 [-0.9725079 ]
 [-0.33831912]]
